name: Test Extension

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

permissions:
  contents: read

jobs:
  validate-composer:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate

  build:

    runs-on: ubuntu-latest

    needs: validate-composer

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/composer-cache

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

  PHP-Compatibility:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/composer-cache

      - name: PHP 8.1 compatibility
        run: composer sniffer:php8.1

  Static-tests:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/composer-cache

      - name: phpstan
        run: composer phpstan

      - name: sniffer
        run: composer sniffer

      - name: mess-detector
        run: composer mess-detector

  PHP-Unit:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/composer-cache

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug

      - name: PHP Unit
        run: composer test

      - name: phpunit-coverage-badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          report: reports/test-reports/clover.xml
          coverage_badge_path: output/coverage.svg
          push_badge: true
          commit_message: "Update coverage badge"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
